
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8082:8082
    container_name: todo-verba-app
    env_file:
      - path: ./app_dev.env
        required: true
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    expose:
      - 5435
    container_name: todo-verba-postgres
    env_file:
      - path: ./db_dev.env
        required: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
