apiVersion: v1
kind: Service
metadata:
  name: todo-verba-db-service
  labels:
    name: todo-vera-db-service
spec:
  type: ClusterIP
  selector:
    app: todo-verba-db
  ports:
    - name: tcp-port
      protocol: TCP
      port: 5435
      targetPort: todo-db-port
