apiVersion: v1
kind: Service
metadata:
  name: todo-verba-app-service
  labels:
    name: todo-vera-app-service
spec:
  type: NodePort
  selector:
    app: todo-verba-app
  ports:
    - name: tcp-port
      protocol: TCP
      port: 30080
      targetPort: todo-app-port
      nodePort: 30080
